### ISSUE TITLE
white-space: pre-line;

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/rosterapp#14]
![image](https://user-images.githubusercontent.com/5037244/79506991-3c36c380-8037-11ea-80be-830bb515c8ac.png)
The text overflows. With pre-line, the \n line breaker works in text. This means that the text can be made to fit.

**Comment by willemm** [comment]
Alternative solution: The very last entry (:last-child) will have word wrap enabled.  This seems to be working fine.  Small niggle: the width is just too wide, sometimes one letter gets cut off.

**Comment by willemm** [comment]
Leave the smal layout things for later
